# Generated by Django 5.1.4 on 2025-08-31 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uprofile", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "用户", "verbose_name_plural": "用户"},
        ),
        migrations.AlterField(
            model_name="profile",
            name="department",
            field=models.CharField(help_text="部门", max_length=120, verbose_name="部门"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="fullname",
            field=models.CharField(help_text="姓名", max_length=120, verbose_name="姓名"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="mobile",
            field=models.CharField(
                blank=True, help_text="手机", max_length=20, verbose_name="手机"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="position",
            field=models.CharField(help_text="职位", max_length=120, verbose_name="职位"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                help_text="用户",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
