# Generated by Django 5.1.4 on 2025-08-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0002_relationshiptable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="medical_record_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="病历号"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
    ]
