# Generated by Django 5.1.4 on 2025-09-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0003_patient_medical_record_number_alter_patient_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="cornealtopography",
            name="raw_data_tangential",
            field=models.JSONField(blank=True, null=True, verbose_name="切向曲率图原始数据"),
        ),
    ]
