# Generated by Django 5.1.4 on 2025-09-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0004_cornealtopography_raw_data_tangential"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="basicparams",
            index=models.Index(
                fields=["patient", "eye", "custom_type"],
                name="patient_bas_patient_66ea07_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cornealtopography",
            index=models.Index(
                fields=["patient", "eye", "BasicParams"],
                name="patient_cor_patient_cf6e2e_idx",
            ),
        ),
    ]
