# Generated by Django 5.1.4 on 2025-09-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0005_basicparams_patient_bas_patient_66ea07_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cornealtopography",
            name="raw_data_axial",
            field=models.JSONField(blank=True, null=True, verbose_name="轴向曲率图原始数据"),
        ),
    ]
