# Generated by Django 5.1.4 on 2025-10-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0006_cornealtopography_raw_data_axial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accustomization",
            name="ai_code",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="AI码"
            ),
        ),
    ]
