# Generated by Django 5.1.4 on 2025-11-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_accustomization_ai_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='export_count',
            field=models.IntegerField(default=0, verbose_name='导出次数'),
        ),
    ]
