# Generated by Django 5.1.4 on 2025-11-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_patient_export_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medment_right_adaptation_status',
            field=models.CharField(default='', max_length=100, verbose_name='Medment右眼适配情况'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medment_right_post_adjustment',
            field=models.CharField(default='', max_length=100, verbose_name='Medment右眼售后调整'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medment_right_satisfaction',
            field=models.CharField(default='', max_length=100, verbose_name='Medment右眼满意度'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medment_right_satisfaction_level',
            field=models.CharField(default='', max_length=100, verbose_name='Medment右眼满意度等级'),
        ),
        migrations.AddField(
            model_name='patient',
            name='seour_right_adaptation_status',
            field=models.CharField(default='', max_length=100, verbose_name='Seour右眼适配情况'),
        ),
        migrations.AddField(
            model_name='patient',
            name='seour_right_post_adjustment',
            field=models.CharField(default='', max_length=100, verbose_name='Seour右眼售后调整'),
        ),
        migrations.AddField(
            model_name='patient',
            name='seour_right_satisfaction',
            field=models.CharField(default='', max_length=100, verbose_name='Seour右眼满意度'),
        ),
        migrations.AddField(
            model_name='patient',
            name='seour_right_satisfaction_level',
            field=models.CharField(default='', max_length=100, verbose_name='Seour右眼满意度等级'),
        ),
        migrations.AddField(
            model_name='patient',
            name='tomey_right_adaptation_status',
            field=models.CharField(default='', max_length=100, verbose_name='Tomey右眼适配情况'),
        ),
        migrations.AddField(
            model_name='patient',
            name='tomey_right_post_adjustment',
            field=models.CharField(default='', max_length=100, verbose_name='Tomey右眼售后调整'),
        ),
        migrations.AddField(
            model_name='patient',
            name='tomey_right_satisfaction',
            field=models.CharField(default='', max_length=100, verbose_name='Tomey右眼满意度'),
        ),
        migrations.AddField(
            model_name='patient',
            name='tomey_right_satisfaction_level',
            field=models.CharField(default='', max_length=100, verbose_name='Tomey右眼满意度等级'),
        ),
    ]
