# Generated by Django 5.1.4 on 2025-11-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_patient_medment_right_adaptation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicparams',
            name='adaptation_status',
            field=models.CharField(default='', max_length=100, verbose_name='适配情况'),
        ),
        migrations.AddField(
            model_name='basicparams',
            name='post_adjustment',
            field=models.CharField(default='', max_length=100, verbose_name='售后调整'),
        ),
        migrations.AddField(
            model_name='basicparams',
            name='review_date',
            field=models.DateField(blank=True, null=True, verbose_name='复查日期'),
        ),
        migrations.AddField(
            model_name='basicparams',
            name='satisfaction_level',
            field=models.CharField(default='', max_length=100, verbose_name='满意度等级'),
        ),
    ]
