# Generated by Django 5.1.4 on 2025-12-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_basicparams_adaptation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medment_left_adaptation_status',
            field=models.CharField(default='', max_length=100, verbose_name='Medment左眼适配情况'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medment_left_post_adjustment',
            field=models.CharField(default='', max_length=100, verbose_name='Medment左眼售后调整'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medment_left_satisfaction',
            field=models.CharField(default='', max_length=100, verbose_name='Medment左眼满意度'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medment_left_satisfaction_level',
            field=models.CharField(default='', max_length=100, verbose_name='Medment左眼满意度等级'),
        ),
    ]
