"""
Django settings for eyehospital project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os



BASE_DIR = Path(__file__).resolve().parent.parent
# 在 settings.py 中

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    
    # 1. 定义日志的格式
    'formatters': {
        'simple': {
            'format': '[%(asctime)s] %(levelname)s %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    
    # 2. 定义处理器 (Handler)，比如 "console"
    'handlers': {
        'console': {
            'level': 'INFO',  # 你可以改为 'DEBUG' 来查看更多信息
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    
    # 3. 定义日志记录器 (Logger)
    'loggers': {
        # 修复这个: Django 自己的 logger
        'django': {
            'handlers': ['console'],
            'level': 'INFO', # Django 自身的日志级别
            'propagate': True,
        },
        # 解决你最初问题的: Matplotlib 的 logger
        'matplotlib': {
            'handlers': ['console'],
            'level': 'WARNING', # 设置为 WARNING，屏蔽 DEBUG 和 INFO
            'propagate': False, # 无需上传
        },
    },
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-xrn-4)ze#ogf%91x)2ly+ddyh=_bx=sae8y4#t=0gc)k3@v(-f"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# 解决跨域
CORS_ALLOWED_ORIGINS = [
    "https://example.com",
    "https://sub.example.com",
    "http://localhost:8080",
    "http://127.0.0.1:9000"
]

# Application definition

INSTALLED_APPS = [
    'simpleui',
    # "django_bootstrap5",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "uprofile",
    "patient",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # "corsheaders.middleware.CorsMiddleware", # 解决跨域
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "eyehospital.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates"),
            # BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "eyehospital.wsgi.application"


# Database 服务器运行
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": "eyehospital",
#         "USER": "root",
#         "PASSWORD": "root",
#         "HOST": "127.0.0.1",
#         "PORT": "3306",
#     }
# }

# 本地运行,数据库配置修改为使用
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('DATABASE_PATH', os.path.join(BASE_DIR, 'db.sqlite3')),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = "/accounts/login/"  # 或其他登录页面路径
LOGOUT_REDIRECT_URL = "/"
LOGIN_REDIRECT_URL = "/"

# 服务器运行，媒体文件配置
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 本地运行，媒体文件配置
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))
MEDIA_URL = '/media/'

# django-simple配置
ADMIN_SITE_HEADER = "OK镜管理后台" # 首页标题
SIMPLEUI_HOME_TITLE = "OK镜管理后台" # 首页标题
SIMPLEUI_HOME_INFO = False  # 服务器信息
# SIMPLEUI_DEFAULT_THEME = 'layui.css'  # 设置为Element-ui风格
SIMPLEUI_CONFIG = {
    # ... 其他配置 ...
    'table_class': 'el-table el-table--striped',  # 添加条纹样式
    'table_row_class': '',  # 如果需要，可以为表格行添加额外的类
}
SIMPLEUI_LOGO = '/static/img/login/FigmaDDSSlicePNGec1bb3b8ecfb646d9187a1d5d20bb31f.png'


# 自定义配置
# 算法类型
ALGORITHM_TYPE = {
    "1": "medment",
    "2": "medment_4",
    "3": "seour",
    "4": "seour_4",
}